version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run build"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
