version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run build"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run test"
  publish:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run deploy"
workflows:
  build-n-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/