version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run build"
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run test"
  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "run deploy"
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/